service: tick
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2 #Write my region 

functions:
  hello:
    handler: handler.tick #Address of my function
    events:
      - httpApi:
          path: /
          method: post #Http Method

# Create a Dynamo DB
resources:
  Resources:
    CustomerTable:
      Type: AWS::DynamoDB::Table #Create table       
      #Setting up my table 
      Properties:
        TableName: tickTable
        BillingMode: PAY_PER_REQUEST 
        #Create my fields 
        AttributeDefinitions:
          - AttributeName: id #Create a primary key 
            AttributeType: S #String as we did 
        KeySchema:  
          - AttributeName: id #The id is my "primary key" 
            KeyType: HASH 