service: tick
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2 #Write my region 
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-2:764539909266:table/tick-dev #This is the arn of dev table
        - arn:aws:dynamodb:us-east-2:764539909266:table/tick-prod #This is the arn of prod table

functions:
  hello: #Name of the lambda in aws
    handler: handler.tick #Address of my function in js
    events:
      - httpApi:
          path: /
          method: post #Http Method

# Create the dynamo dev table
resources:
  Resources:
  # Dev table
    devTable:
      Type: AWS::DynamoDB::Table #Create table       
      #Setting up my table 
      Properties:
        TableName: tick-dev
        BillingMode: PAY_PER_REQUEST 
        #Create my fields 
        AttributeDefinitions:
          - AttributeName: id #Create a primary key 
            AttributeType: S #String as we did 
        KeySchema:  
          - AttributeName: id #The id is my "primary key" 
            KeyType: HASH
  # Prod table
    prodTable:
      Type: AWS::DynamoDB::Table #Create table       
      #Setting up my table 
      Properties:
        TableName: tick-prod
        BillingMode: PAY_PER_REQUEST 
        #Create my fields 
        AttributeDefinitions:
          - AttributeName: id #Create a primary key 
            AttributeType: S #String as we did 
        KeySchema:  
          - AttributeName: id #The id is my "primary key" 
            KeyType: HASH