service: tick
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2 #Write my region 

functions:
  hello:
    handler: handler.tick #Address of my function
    events:
      - httpApi:
          path: /
          method: post #Http Method
